version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: unix
    env:
      - CGO_ENABLED=0
    main: ./cmd/rizznet
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
      - -tags=netgo 
    ldflags:
      - -s -w

  - id: windows
    env:
      - CGO_ENABLED=0
    main: ./cmd/rizznet
    goos:
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
      - -tags=netgo
    ldflags:
      - -s -w

archives:
  - id: nix
    ids:
      - unix
    formats:
      - tar.gz
    # Include the files prepared by 'make prepare-release'
    files:
      - src: config.yaml
      - src: GeoLite2-ASN.mmdb
      - src: GeoLite2-Country.mmdb
      - src: LICENSE
      - src: README.md

  - id: windows
    ids:
      - windows
    formats:
      - zip
    # Include the files here as well
    files:
      - src: config.yaml
      - src: GeoLite2-ASN.mmdb
      - src: GeoLite2-Country.mmdb
      - src: LICENSE
      - src: README.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
